name: John Eder Event Photography
favicon: null
layout_spectrum: 0.7055680293124169
typography_spectrum: 0.5550321952905506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.26229770365171134
  lightness: 0.12105503026396036
  saturation: 0.5671286042779684
  rhythmicContrast: 0.268439986044541
purpose: []
